### ISSUE TITLE
DXF - SSurveyingFormat.ImportProject

### ISSUE THREAD

**Issue by Pierro2100** [3DReshaper/Scripts#1]
Hello everyone.

I started recently in 3dr script.
And I'm stuck on an import function of a dxf.
I would like to know what type of object I get with the SSurveyingFormat.ImportProject function and be able to perform operations on it (intersection, measurements ...)
For now I can not do any operation on the result of this import.

Thank you for your help

`var DossierScript = CurrentScriptPath();
var Theorique =SSurveyingFormat.ImportProject(DossierScript +'/K34/226.dxf');

var Theorique = Theorique.PolyTbl;
Theorique.forEach(function(obj)
{
	obj.AddToDoc();
});`

**Comment by Technodigit** [comment]
Bonjour/Hello
Please send us your email address to support@3dreshaper.com to get a reply
Thank you / Merci
